### ISSUE TITLE
[DMCA]请仔细思考关于将qn从鸣谢列表去除一事

### ISSUE THREAD

**Issue by qwq233** [GoldenHuaji/QScript#1]
如果您确定删除所有有关qn的代码的话忽略即可，否则，请保留所有涉及文件的完整代码头，这包括但不限于仅更改各种名称、更改代码顺序等。
这是仅一次警告，若长期未获得回复，将会考虑采取进一步措施

**Comment by GoldenHuaji** [comment]
？所有代码头均已保留

**Comment by GoldenHuaji** [comment]
任何从QN拷贝的代码均已保留代码头，有没有保留的能说一下吗？

**Comment by qwq233** [comment]
> 任何从QN拷贝的代码均已保留代码头，有没有保留的能说一下吗？

根据GPL只要涉及一点都会强制传播
相似逻辑或者只是java->kt同理

**Comment by GoldenHuaji** [comment]
好，下个 commit 加上去

**Comment by GoldenHuaji** [comment]
已经提交了，看看可以吗？
所有的从 QN 拷贝的代码已经 加上了 `@FromQNotified`，并且含有`@FromQNotified`的文件里含有QN的代码头（在 package .. 的下面）

**Comment by GoldenHuaji** [comment]
请问仍然需要把QN从“开源许可”里面移除吗？

**Comment by qwq233** [comment]
> 请问仍然需要把QN从“开源许可”里面移除吗？

在最上面写代码头 而不是用你的代码头替换
在放不放特别鸣谢貌似GPL没硬性要求

**Comment by GoldenHuaji** [comment]
好的

**Comment by GoldenHuaji** [comment]
提交了，看一下可以吗？

**Comment by qwq233** [comment]
可以了，谢谢
对了，顺便看一下你git是不是设置有问题 github没检测出你 commit全部戳不开个人信息页
