### ISSUE TITLE
脚本问题

### ISSUE THREAD

**Issue by 3228222175** [GoldenHuaji/QScript#2]
无法导入我自己的脚本啊
![Screenshot_2021-02-17-18-09-36-35](https://user-images.githubusercontent.com/68888829/108202859-b0ad2800-715c-11eb-81eb-0daed1aaa0f4.jpg)

**Comment by GoldenHuaji** [comment]
请仔细阅读 [Wiki](https://github.com/GoldenHuaji/QScript/wiki/%E5%B8%AE%E5%8A%A9---%E5%85%B3%E4%BA%8E%E8%84%9A%E6%9C%AC#%E8%84%9A%E6%9C%AC%E6%9C%89%E4%BB%80%E4%B9%88%E6%A0%BC%E5%BC%8F%E5%90%97)
